spring:
  application:
    name: eureka
  security:
    basic:
      enabled: true
    user:
      name: ${EUREKA_BASIC_USER:admin}
      password: ${EUREKA_BASIC_PASSWORD:admin}

eureka:
  client:
    security:
      basic:
        user: ${spring.security.user.name}
        password: ${spring.security.user.password}
    service-url:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@${EUREKA_SERVER_HOST:127.0.0.1}:${server.port}/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true

server:
  port: ${SERVER_PORT:8762}
