{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "samples.serviceAccountName" . }}
  labels:
{{ include "samples.labels" . | nindent 4 }}
{{- end -}}
